version: '2'

services:
    app:
        image: alpine
        command: /bin/sh
        volumes:
            - ./app:/var/www/html

    proxy:
        image: jwilder/nginx-proxy
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        ports:
            - ${PROXY_PORT}:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx:
        build: ./docker/build/nginx
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
        links:
            - app
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        volumes_from:
            - app

    php:
        build: ./docker/build/php
        environment:
            - NODE_ENV=${NODE_ENV}
            - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS}
            - PHP_DISPLAY_STARTUP_ERRORS=${PHP_DISPLAY_STARTUP_ERRORS}
            - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING}
            - PHP_CLI_MEMORY_LIMIT=512M
            - PHP_FPM_MEMORY_LIMIT=128M
            - PHP_FPM_POST_MAX_SIZE=8M
            - PHP_FPM_UPLOAD_MAX_SIZE=2M
            - PHP_FPM_XDEBUG_EXTENSION=${PHP_FPM_XDEBUG_EXTENSION}
        extra_hosts:
            - dockerhost:${DOCKERHOST}
        links:
            - app
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        volumes_from:
            - app

    redis:
        build: ./docker/build/redis
        command: redis-server /usr/local/etc/redis/redis.conf ${REDIS_PARAMETERS}
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - redis:/data

    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${RDMS_DATABASE}
            - MYSQL_USER=${RDMS_USER}
            - MYSQL_PASSWORD=${RDMS_PASSWORD}
        image: mysql:5.7
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - mysql:/var/lib/mysql

volumes:
    redis:
        driver: local

    mysql:
        driver: local
