version: '2'

services:
    app:
        image: alpine
        command: /bin/sh
        volumes:
            - ./app:/opt/project

    nginx:
        build: ./docker/build/nginx
        env_file: .env
        links:
            - app
        logging:
            driver: json-file
            options:
                max-size: ${SERVICE_LOG_SIZE}
                max-file: ${SERVICE_LOG_ROTATE}
        ports:
            - ${PROXY_PORT}:80
        volumes_from:
            - app

    php:
        build: ./docker/build/php
        env_file: .env
        extra_hosts:
            - dockerhost:${XDEBUG_HOST}
        links:
            - app
        logging:
            driver: json-file
            options:
                max-size: ${SERVICE_LOG_SIZE}
                max-file: ${SERVICE_LOG_ROTATE}
        volumes_from:
            - app

    mysql:
        env_file: .env
        image: mysql:5.7
        logging:
            driver: json-file
            options:
                max-size: ${SERVICE_LOG_SIZE}
                max-file: ${SERVICE_LOG_ROTATE}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
        driver: local
