version: '2'

services:
    app:
        image: alpine
        command: /bin/sh
        volumes:
            - ./app:/var/www/html

    proxy:
        image: jwilder/nginx-proxy
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        ports:
            - ${PROXY_PORT}:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx:
        build: ./docker/build/nginx
        env_file: .env
        links:
            - app
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        volumes_from:
            - app

    php:
        build: ./docker/build/php
        env_file: .env
        extra_hosts:
            - dockerhost:${XDEBUG_HOST}
        links:
            - app
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        volumes_from:
            - app

    redis:
        build: ./docker/build/redis
        command: redis-server /usr/local/etc/redis/redis.conf ${REDIS_PARAMETERS}
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - redis:/data

    mysql:
        env_file: .env
        image: mysql:5.7
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE}
                max-file: ${LOG_ROTATE}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - mysql:/var/lib/mysql

volumes:
    redis:
        driver: local

    mysql:
        driver: local
